[tool.poetry]
name = "mbmm"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.7"
pyside6 = "^6.8.0.2"
mysql-connector-python = "^9.1.0"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
